create table if not exists public.bot_state (
  owner_id text not null,
  key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (owner_id, key)
);

alter table public.bot_state enable row level security;

create table if not exists public.bot_events (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  type text not null,
  symbol text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.bot_events enable row level security;

create index if not exists bot_events_owner_created_idx
  on public.bot_events (owner_id, created_at desc);

